last version

diff --git a/.github/workflows/laravel.yaml b/.github/workflows/laravel.yaml
--- a/.github/workflows/laravel.yaml
+++ b/.github/workflows/laravel.yaml
@@ -70,7 +70,7 @@ jobs:
         with:
           node-version: '20'
           cache: 'npm'
-          cache-dependency-path: frontend/package-lock.json  # Point to your lock file
+          cache-dependency-path: frontend/package-lock.json  
 
       - name: Check Node.js and NPM versions
         run: |
@@ -79,6 +79,17 @@ jobs:
 
       - name: Navigate to frontend directory
         run: cd frontend
+      - name: Debugging Output
+        run: |
+          pwd
+          ls -la
+
+      - name: Verify lock file
+        run: |
+          if [ ! -f package-lock.json ] && [ ! -f npm-shrinkwrap.json ] && [ ! -f yarn.lock ]; then
+            echo "Lock file not found in the frontend directory. Exiting."
+            exit 1
+          fi
 
       - name: Install Dependencies (React)
         run: npm install
